version: '3'
services:
  mitmproxy:
    build:
      context: mitmproxy
    image: ops-mitmproxy
    restart: always
    command: ["mitmweb", "--web-iface", "0.0.0.0"]
    ports:
      - "8081:8081"
      - "8080:8080"