version: '3'
services:
  prometheus:
    build:
      context: prometheus
    image: ops-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /data/db/prometheus/:/prometheus/
      - /data/conf/prometheus/:/etc/prometheus/
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.external-url=http://localhost:81
    restart: always
    networks:
      - app
      - ops
  alertmanager:
    image: prom/alertmanager
    #restart: always
    volumes:
      - /data/conf/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - ops
      - app
networks:
  app:
    external: true
  ops:
    external: true