version: '3' 
services:
  clickhouse:
    build:
      context: clickhouse
      args:
        - VERSION=19.16
    image: db-clickhouse:19.16
    ports:
      - "8123:8123"
      - "8124:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /data/db/clickhouse/:/var/lib/clickhouse/
      - /data/conf/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - /data/conf/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - /data/conf/clickhouse/dict/:/etc/clickhouse-server/dict/
      - /data/logs/clickhouse/server/:/var/log/clickhouse-server/
    restart: always
    networks:
      - db
networks:
  db:
    external: true