ARG VERSION
FROM php:${VERSION}-fpm

LABEL author="auho auho@163.com"

RUN apt-get update \
    && apt-get install -y libmemcached-dev zlib1g-dev libssl-dev \
    && echo "Asia/Shanghai" > /etc/timezone \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    
RUN pecl channel-update https://pecl.php.net/channel.xml \
    && docker-php-ext-install mysql mysqli pdo_mysql \
    && pecl install xdebug-2.5.5 \
    && docker-php-ext-enable xdebug

RUN apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-jpeg-dir --with-freetype-dir \
    && docker-php-ext-install gd