version: '3' 
services:
  php:
    build:
      context: php
      args:
        - VERSION=7.3
    image: app-php:7.3
    volumes:
      - /data/conf/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /data/conf/php/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - /data/logs/php/:/var/log/php/
      - /data/www/:/data/www/
    extra_hosts:
      - "xxx:127.0.0.1"
    restart: always
    networks:
      - app
      - db
networks:
  app:
    external: true
  db:
    external: true
