version: '3' 
services:
  nginx:
    build:
      context: nginx
      args:
        - VERSION=1.17
    image: app-nginx:1.17
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/conf/nginx/conf.d/:/etc/nginx/conf.d/
      #- /data/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/www/:/data/www/
      - /data/logs/nginx/:/var/log/nginx/
    restart: always
    networks:
      - app
networks:
  app:
    external: true
  db:
    external: true
